name: create-release

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: 0.0.0
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      CI: true

    strategy:
      matrix:
        node-version: [12.16.1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: App build
        working-directory: ./app
        run: |
          npm i
          npm run test:coverage
          npm run build

      - name: Bump package version
        working-directory: ./app
        run: PACKAGE_VERSION=$(npm version minor)

      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        with:
          tag_name: $PACKAGE_VERSION
          release_name: $PACKAGE_VERSION
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false