name: PR lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
     
  pr-lint:
    env:
      server-dir: server
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.1]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # set up Node.js runner
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # debug
      - name: debug
        run: pwd && ls -la

      # app actions
      - name: app build
        working-directory: ./app
        run: |
          npm i
          npm run build
